"""AdditionalInfo, Technology, Task are added

Revision ID: 9a30aff5439a
Revises: f255d59f917b
Create Date: 2021-07-06 19:14:38.620284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a30aff5439a'
down_revision = 'f255d59f917b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('info')
    )
    op.create_table('technology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=True),
    sa.Column('finishDate', sa.DateTime(), nullable=True),
    sa.Column('usageCase', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=150), nullable=True),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('technology')
    op.drop_table('additional_info')
    # ### end Alembic commands ###
