"""Initial migration

Revision ID: f255d59f917b
Revises: 
Create Date: 2021-07-06 19:01:10.299710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f255d59f917b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('info')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('additional_info')
    # ### end Alembic commands ###
